import { IsString, IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class UpdateFcmTokenDto {
  @ApiProperty({ example: 'ezX_abc123...', description: 'The FCM device token generated by the mobile app' })
  @IsString()
  @IsNotEmpty()
  fcmToken: string;
}